### ISSUE TITLE
Panic in src/responder.rs:114:18  { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable }

### ISSUE THREAD

**Issue by int08h** [int08h/roughenough#33]
Full log message was:

`
thread 'main' panicked at 'send_to failed: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/responder.rs:114:18
`

Seen on `roughtime.int08h.com`

**Comment by int08h** [comment]
Backtrace of bug

`
Nov 27 23:45:15 roughenough-1f run_server.bash[3662]:    1: core::panicking::panic_fmt
Nov 27 23:45:15 roughenough-1f run_server.bash[3662]:              at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
Nov 27 23:45:15 roughenough-1f run_server.bash[3662]:    2: core::result::unwrap_failed
Nov 27 23:45:15 roughenough-1f run_server.bash[3662]:              at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
Nov 27 23:45:15 roughenough-1f run_server.bash[3662]:    3: roughenough::responder::Responder::send_responses
Nov 27 23:45:15 roughenough-1f run_server.bash[3662]:    4: roughenough::server::Server::process_events
Nov 27 23:45:15 roughenough-1f run_server.bash[3662]:    5: roughenough_server::main
`

**Comment by int08h** [comment]
Fix has been deployed
